### PR TITLE
FreeBSD and MacOS related fixes and improvements: compilation and serial port access

### PR DESCRIPTION
**Pull request by samm-git**
First of all thank you for all your work! I found that ebusd does not work on the FreeBSD out of the box and fixed that. I think this would be the same on OSX, but did not checked yet.

Here is a detailed description:

1. I am adding ` #include <netinet/in.h>` to fix compilation error related to undefined  `sockaddr_in`. It does not break Linux compilation, so no ifdefs.
2. Serial port access in the `device.cpp` is broken for the number of reasons:
    - call to `open` without `O_NDELAY` will wait for DCD line forever. `O_NDELAY` sets port to non-blocking mode, so it is does not happens. Later you are configuring it anyway, so should not affect anything else.
    - Linux is storing speed in the `c_cflag` but FreeBSD and MacOS are using different variable for that. Using POSIX `cfsetspeed` we can use same call for different OS. 
    - Checking return code of the `tcsetattr`, as it was failing due to previous reason but nothing was reported back to user
3. Add low latency flag for the UFTDI driver. I did not found any global latency flag on the FreeBSD, so doing this for the FTDI only as for now. Also checked that other drivers do not have similar ioctl.

With these changes ebusd works for me.

### CODE REVIEW

**Comment by samm-git** [comment]
Tested on OSX - without fix issue is the same (hang on open()). After fix works as intended.

**Comment by john30** [comment]
you seem to have removed the serial.h check for non-BSD low latency checking from configure.ac. please check if everything still works for you after 595d1dd

**Comment by samm-git** [comment]
Thank you, will do and apologize for removal of the linux def. I am going to submit official freebsd port soon, do you plan to release new versions in the meantime? If not i will just use my patch for the latest release.

**Comment by john30** [comment]
version 3.4 will probably be released soon

**Pull request merged**
