### PR TITLE
Create version 21.3, upgraded dockerfiles to bullseye

### PR DESCRIPTION
**Pull request by GrumpyMeow**
Hi @john30 ,

I've taken the liberty/initiative to create version 21.3. This would help me and others to resolve the issue with the MQTT version-check. I'm also working on a "Homeassistant eBUSd add-on".

I hope you find the time/energy to officially publish version 21.3.

Thanks in advance,
Sander Schutten

### CODE REVIEW

**Comment by netweaver1970** [comment]
thanks for the effort, now I'm keeping another Raspi, next to my HA box, just as a holder for the ebusd container. And I think I'm not the only one ...
So being able to combine them would be nice :)

**Comment by GrumpyMeow** [comment]
> thanks for the effort, now I'm keeping another Raspi, next to my HA box, just as a holder for the ebusd container. And I think I'm not the only one ...
> So being able to combine them would be nice :)

Myself I’ve just “discovered” Proxmox and HassIO. It’s so hassle free. I’m working on a ebusd-hassio-addon. For this I need the PR also  myself.

**Comment by moskovskiy82** [comment]
@GrumpyMeow thank you for the effort. Awaiting the HassIO addon. I know this is not the right place but is there any tutorial for the ebusd? The documentation for ebusd daemon is not straightforward if installing via the repo.

**Comment by netweaver1970** [comment]
@GrumpyMeow now the official docker version is out, with bullseye and extra mqtt support versions, is it enough to continue your HomeAssistant integration? Looking forward to it !

Thanks.

**Comment by john30** [comment]
done

**Comment by GrumpyMeow** [comment]
@netweaver1970 I've tried to update the addon, but unfortunately v21.3 is not registered everywhere yet. 
I think the "ebusd-debian" needs to be updated also. For now i'm gonna wait and see if that repo will also be updated.

**Comment by john30** [comment]
it is in the assets of the [latest release](https://github.com/john30/ebusd/releases/latest)

**Pull request closed without merging**
