### PR TITLE
Update mqtt-hassio.cfg to include humidity

### PR DESCRIPTION
**Pull request by apbarratt**
This seemed like such a benign but interesting (to me at least😅) addition to the list of filtered data that I figured no harm could be done in including it in the original template :)

### CODE REVIEW

**Comment by apbarratt** [comment]
Screenshot 2023-11-27 at 13 43 41
Quicky screenshot of the room humidity value coming from my Vailant thermostat :)
I'll confess I don't know why it is called maxRoomHumidity.

**Comment by tpires** [comment]
fyi: looking to my vrc700/6 and this value is not the room humidity. currently is at `66%` and MaxRoomHumidtity is set to `60`

**Comment by pepsonEL** [comment]
But is any chance to read actual humidity from VRC700/6 ?

**Comment by tpires** [comment]
the value is available on the advanced menu of VRC700/6, so I'd say yes. just a matter of mapping the address of the value?

**Comment by pepsonEL** [comment]
Yes you are true. But how ?

**Pull request merged**
