### PR TITLE
Build ebusd with knxd support as Docker container

### PR DESCRIPTION
**Pull request by c-huetter**
There are several discussions on knx-user-forum.de that ask for an ebusd release with built-in knxd support. Since I had the same requirement, I have added a build target for Docker containers with knxd support.

### CODE REVIEW

**Comment by c-huetter** [comment]
I have added a bugfix for issue #1074 to this branch. Please verify the bugfix and consider merging the pull request.

**Comment by mivola** [comment]
> I have added a bugfix for issue #1074 to this branch. Please verify the bugfix and consider merging the pull request.

Maybe it would be better to create a dedicated PR for this fix?

**Comment by c-huetter** [comment]
I can do whatever is more convenient for @john30

**Comment by c-huetter** [comment]
Dear John,

Thank you so much for fixing the KNX data point bug and for including knxd support in the container images. Seasons greetings to you and a successful new year!

Best
Christian

**Pull request closed without merging**
